# Playbook to set up the lab

---
- include: setup-hosts.yml
- include: setup-infrastructure.yml
- include: os-keystone-install.yml
- include: os-glance-install.yml
- include: os-nova-install.yml
- include: os-neutron-install.yml
- include: os-heat-install.yml
- include: os-ceilometer-install.yml
- include: ovs-setup.yml